### ISSUE TITLE
Project 2 - Kadumya Website

### ISSUE THREAD

**Issue by n-orah** [WDI-HoneyBadger/project-2#1]
**Project Name:** KADUMYA - كدُمية (Like a doll).

- It is an original Saudi brand, we sell original pieces that made in Saudi.
- Models needed are 2: The first one is a page full of items that have heart buttons. The second one is the user hitting the heart button that can save the items they like.
**Wireframes (Animated):** https://xd.adobe.com/view/76c57313-df32-450f-485c-55e947fdc65d-00f4/
(Click the buttons to see the other pages.)
- I do not have a specific timeline. 
**NPM Package:** https://www.npmjs.com/package/css-animation
**Challenge:** To make it a real website for our business.
**Repo:** https://github.com/n-orah/project-2

**Comment by trevorpreston** [comment]
looking good!  👍

**Comment by trevorpreston** [comment]
hey Norah, circling back on this - I noticed that the wireframes and your proposal don't line up.  What is the shopping cart for?  Are you going to have users be able to add things to a cart as well as to their favorites?

**Comment by n-orah** [comment]
Hi @trevorpreston,
Here you go!
https://imgur.com/a/7YTazwn

**Comment by trevorpreston** [comment]
Nice.  That's looking good.  So is there not a shopping cart or checkout feature?  I would recommend against it, that's going to add a lot of complications to a project that's already somewhat challenging.

**Comment by n-orah** [comment]
I agree with you! That's why I canceled the shopping cart feature.

**Comment by trevorpreston** [comment]
Right, this looks good.  And then you would have CRUD functionality for the user?

**Comment by n-orah** [comment]
Yes! I will use READ for likes and DELETE when the user unlike the product.

**Comment by trevorpreston** [comment]
looks good!  👍
