### ISSUE TITLE
Project 2 

### ISSUE THREAD

**Issue by layalkashgari** [WDI-HoneyBadger/project-2#10]
Tuesday - Project Proposals: Due Tonight! 📆
Your proposal should include:
Name of your app

**The N/A Football club** 

What your app does

The app has 

The models you need for your app and any relationships

**players 
schedule** 

Wireframes!
**Home Page Wireframe:** 
https://wireframe.cc/NtN2nQ 

**Schedule Page Wireframe:** 

https://wireframe.cc/DJplKC

**View Player Details** 

https://wireframe.cc/a4JTUz

A timeline laying out what you're going to do each day. This should specify clear features to be implemented by the end of each day. 

A link to the NPM package you intend to use.
https://www.npmjs.com/package/calendar

Foreseen challenges or obstacles

Technology you intend to use

A link to your repo!

https://github.com/layalkashgari/Project2.git

**Comment by trevorpreston** [comment]
good project!  Approved 👍
