### ISSUE TITLE
project 2

### ISSUE THREAD

**Issue by hananalshammary** [WDI-HoneyBadger/project-2#12]
Name of your app: 
 frozenyogurt

Technology: javascript , html , Css
A link to the NPM package:https://www.npmjs.com/package/vue-receipt-component

A link to your repo!:
https://github.com/hananalshammary?tab=repositories

https://wireframe.cc/TFvnAJ

**Comment by trevorpreston** [comment]
hey Hanan,

Just one question:  What are your two models and what is their relationship?

**Comment by hananalshammary** [comment]
hi
I have 2 models relationship one to many

‫في الأحد، 16 ديسمبر 2018 في 10:56 ص تمت كتابة ما يلي بواسطة ‪Trevor
Preston‬‏ <‪notifications@github.com‬‏>:‬

**Comment by hananalshammary** [comment]
model for order and model for yogurt.

I will use npm vue-receipt-component:
 https://www.npmjs.com/package/vue-receipt-component

**Comment by trevorpreston** [comment]
Hey Hanan,

You'll have to find another npm package.  That package is for a specific piece of software called Vue that we are not using.  Otherwise looking like a good project.  Approved 👍
