### ISSUE TITLE
Project 2 Beauti-U

### ISSUE THREAD

**Issue by AlanoudBinSalamah** [WDI-HoneyBadger/project-2#13]
**Beauti-U:**

- It is an application that makes the user between hair-stylist or makeup-artist and book an appointment with them.

**Models & relationships** :

- two models for both hair-stylist and makeup-artist that have relationship with the user

**Wireframe:**

- https://wireframe.cc/HO9eim

**Technology used :**

- HTML
-CSS
- Js
- SQL
- npm

**Foreseen challenges:**

- the project its self is a challenge but if I would , I'm anticipating that using new npm packages would be rather challenging more

**Link to my repo:**
https://github.com/AlanoudBinSalamah?tab=repositories

**Comment by trevorpreston** [comment]
hey Alanoud,

This is looking good!  As a suggestion you may want to make this for only hair-stylists or only makeup-artists at first.  Then add the other one later.  When do you have both you could also add them to the same table, like a "stylist" table.  Then in the stylist table have a column for "type", where the value can be "makeup" or "hair".

Looking good!  Approved 👍
