### ISSUE TITLE
Project#2

### ISSUE THREAD

**Issue by MayMo7a** [WDI-HoneyBadger/project-2#14]
- Name of your app
Life hack
 
- What your app does
Hack in different categories which supposed to make your life easy.
I guarantee nothing, don't try it 😜

- The models you need for your app and any relationships
3 models categories, hacks post and users who type and upload the hacks 'photos, videos' 
 
- Wireframes!
- A timeline laying out what you're going to do each day. This should specify clear features to be implemented by the end of each day.

- A link to the NPM package you intend to use.
I did a quick research about something will allow me to upload pics, videos and I found 'express-fileupload, multer, Cloudinary'. I need to dig dipper to see which one fit the app, easy to apply.

- Foreseen challenges or obstacles
Apply new npm package
Make the app functional, something I can be proud of 

- Technology you intend to use
HTML/CSS
JS
NPM
SQL

- A link to your repo!
https://github.com/MayMo7a/project2

**Comment by trevorpreston** [comment]
looks good!  👍
