### ISSUE TITLE
Ethar  - إيثار

### ISSUE THREAD

**Issue by Mohrah-Alateeq** [WDI-HoneyBadger/project-2#15]
- Name : 
Ethar  - إيثار

- Models :
 1-Organization model 
 2-Volunteers model

- Relationships:
1-Add
2-Edit
3-Delete
4-Find
5-Git all

- Wireframe :
file:///Users/mohrahalateeq/Desktop/Wireframe.cc%20-%20minimal%20wireframing%20tool.webarchive

- Timeline 
Design (start: 14/12  end: 15/12   )
Development (start: 15/12  end: 18/12   )
Execution (start: 18/12  end: 18/12   )
test (start: 19/12  end: 19/12   )

- NPM:
npm calendar

- Technology:
 Html , javascript , css

**Comment by trevorpreston** [comment]
looks good!  👍
