### ISSUE TITLE
For the sake of cake

### ISSUE THREAD

**Issue by arfajraa** [WDI-HoneyBadger/project-2#16]
Name:-
For The Sake of Cake

Description:-
E-commerce web app to order amazing cakes.

Models and relationships:-
User. Order. Cake. Order_items. One to many relationship between users and orders. One to many relationship between order and order_items. One to many relationship between product and order_items. 

Wireframes:-
https://xd.adobe.com/view/592f45d0-b3f2-470f-7b8c-fa0da1275834-2f1e/

TIMELINE (will probably jump around between things to make sure they work):-
Sunday: database and most of the models.
Monday: models and most of the controllers.
Tuesday: controllers and most of the views.
Wednesday: views and styling.
Thursday: final touch up and presentation.

NPM package I plan to use:-
https://www.npmjs.com/package/paypal-checkout

Foreseen challenges or obstacles:-
Users authentication, payments, models might get complex with an order having multiple order_items

Technologies:-
MVC RESTful app using express, postgres and our familiar packages.

Link to repo:-
https://github.com/arfajraa/For-The-Sake-of-Cake

**Comment by trevorpreston** [comment]
looks good!  👍
