### ISSUE TITLE
khld project proposal

### ISSUE THREAD

**Issue by khalidnt** [WDI-HoneyBadger/project-2#17]
RSVP Portal
this app manages manages attendance at events.
A model for guests (showAll, show, edit, new)  A model for events(showAll, show, edit, new, 
delete). RSVP. edit RSVP. 
https://xd.adobe.com/view/b5d78b9a-da2b-4bee-6499-56d2e833c8f6-c3e6/?hints=off
Saturday: scaffolding. Monday: models and controllers. Tuesday: views and css. Wednesday: auth.
https://www.npmjs.com/package/qr
display of QR might be an obstacle. making the site "pretty" 
Intend to use MVC
https://github.com/khalidnt/RSVP

**Comment by trevorpreston** [comment]
Sounds good.  Are you going to have users?

**Comment by khalidnt** [comment]
the dummy data you mean? yeah. will finish the seed file

**Comment by trevorpreston** [comment]
Alright sounds good!  👍
