### ISSUE TITLE
project 2 - ProMa website 

### ISSUE THREAD

**Issue by aishah21** [WDI-HoneyBadger/project-2#18]
### Name of your app:
 ProMa website 
### What your app does :
 it's project management app 
### A timeline: 
- create a database 
- create  folders and files  
- configuration 
- quires  
- pages and style 
### Wireframes!
![image](https://user-images.githubusercontent.com/30210097/49966000-d5c7ff80-ff2f-11e8-91e0-2056af4d07c6.png)

 ### challenges  :  
user privilege 
### Technology you intend to use: 
HTML , css , js 
### A link to your repo!: 
https://github.com/aishah21/ProMa-

**Comment by trevorpreston** [comment]
This sounds good.  Could you tell me what the relationships are for your models before it's approved?

**Comment by aishah21** [comment]
<img width="576" alt="relationships" src="https://user-images.githubusercontent.com/30210097/50053267-13e93d00-0143-11e9-9f90-ba9f51f9de1e.png">

<img width="730" alt="route" src="https://user-images.githubusercontent.com/30210097/50053269-18adf100-0143-11e9-8f69-1d930f2a3a10.png">

**Comment by trevorpreston** [comment]
Looking good!  Ambitious, but I'm a believer.  👍
