### ISSUE TITLE
Project 2 

### ISSUE THREAD

**Issue by jalharbi** [WDI-HoneyBadger/project-2#19]
**Name of your app**
NSE stands for Never Stop Exploring 
**What your app does**
My app guide a traveler to the best places that he/she visit once they are in specific country or city, including the best worthy sightseen, little info, best activities, history, and some pictures
**The models you need for your app and any relationships**
I will need 4 modules and 4 controllers 
**Wireframes!**
![screen shot 2018-12-14 at 12 08 08 am](https://user-images.githubusercontent.com/44347549/49968916-3c511b80-ff38-11e8-85bc-dba9f0d527b9.png)
![screen shot 2018-12-14 at 12 16 37 am](https://user-images.githubusercontent.com/44347549/49968923-41ae6600-ff38-11e8-8734-a6218a55f1aa.png)
![screen shot 2018-12-14 at 12 26 19 am](https://user-images.githubusercontent.com/44347549/49968936-46731a00-ff38-11e8-9ef3-e9ed4a75d85e.png)

**A timeline laying out what you're going to do each day. This should specify clear features to be implemented by the end of each day.**
friday > finishing the idea of the app
sat>start creating the folders and install the express
sun> start creating database coding modules and the controllers
mon> continue working on modules and controllers
tus> create the comment and edit and delete buttons
wed> styling - review the work 
thurs> present the app to the class 

**A link to the NPM package you intend to use.**
still looking for it 
**Foreseen challenges or obstacles**
add the sign in and sign out buttons / add the comments options
**Technology you intend to use**
JS,SQL,HTML,Express and all the stuff
**A link to your repo!**
https://github.com/jalharbi/project-2.git

**Comment by trevorpreston** [comment]
Looks good!
