### ISSUE TITLE
 online coffee 

### ISSUE THREAD

**Issue by talomari01** [WDI-HoneyBadger/project-2#2]
https://wireframe.cc/DlbTPo

**Comment by trevorpreston** [comment]
hey Turki,

Can you please fill out all the field for the proposal?  

Your proposal should include:
Name of your app
What your app does
The models you need for your app and any relationships
Wireframes
A timeline laying out what you're going to do each day. This should specify clear features to be implemented by the end of each day.
A link to the NPM package you intend to use.
Foreseen challenges or obstacles
Technology you intend to use
A link to your repo!

**Comment by talomari01** [comment]
My app is to order coffee online on the campus, and I will use 2 models. I'm going to use CSS, Html, javascript.

**Comment by trevorpreston** [comment]
What are your modes, what are their relationships?
You only have one wireframe, does that mean your app will only be one page?
What are your foreseen challenges and obstacles?
What is the link to your repo?

please, thank you

**Comment by trevorpreston** [comment]
Could you also spruce up your wireframes for this app?  It needs more details.  I'll get off your back once I have those, promise 😅

**Comment by talomari01** [comment]
![screen shot 2018-12-16 at 5 25 53 pm](https://user-images.githubusercontent.com/44371980/50054879-17d38a00-0158-11e9-851c-cefe6aacf913.png)

**Comment by trevorpreston** [comment]
Looking good 👍
