### ISSUE TITLE
Project 2 

### ISSUE THREAD

**Issue by Bader1011** [WDI-HoneyBadger/project-2#20]
The idea of this app, will be to connect people with each other when they need someone to sharing the food with them 

https://wireframe.cc/U93oEF

**Comment by trevorpreston** [comment]
Hey Bader, could you update this with all the required info?  Thanks.

required info:
Name of your app
What your app does
The models you need for your app and any relationships
Wireframes!
A timeline laying out what you're going to do each day. This should specify clear features to be implemented by the end of each day.
A link to the NPM package you intend to use.
Foreseen challenges or obstacles
Technology you intend to use
A link to your repo!

**Comment by Bader1011** [comment]
> Hey Bader, could you update this with all the required info? Thanks.
> 
> required info:
> Name of your app: "be together" 

> What your app does: It is allow people to communicate together and have food their favourite food together and make the society more sociable.

> The models you need for your app and any relationships: "user" and "food"

> Wireframes!: I done it already.  

> A timeline laying out what you're going to do each day. This should specify clear features to be implemented by the end of each day: Monday: link html pages with the  database. Tuesday: create Edit and Delete buttons that will allow users to edit and delete their info,  Wednesday: styling CSS and review the bugs. Write README.

> A link to the NPM package you intend to use: https://www.npmjs.com/package/bootstrap

> Foreseen challenges or obstacles: to save previous users request "hangout" and put it  in their file as a history .

> Technology you intend to use: HTML , CSS , JS and  SQL.

> A link to your repo! : https://github.com/Bader1011/Project2

**Comment by trevorpreston** [comment]
👍
