### ISSUE TITLE
Project-2

### ISSUE THREAD

**Issue by Rawandahli** [WDI-HoneyBadger/project-2#21]
Name of the app:
Storm It 
What the app does:
An online brain storming session.
The models I need for my app and relationships:

Wireframes:
images.githubusercontent.com/44443628/49995494-5d982300-ff9d-11e8-91a9-fc38de6afc93.png)
https://wireframe.cc/QKSbBa

mages.githubusercontent.com/44443628/49995881-7c4ae980-ff9e-11e8-9c8c-2951856761b3.png)
https://wireframe.cc/Mqlz5j

A link to the NPM package you intend to use:

Foreseen challenges or obstacles:

Technology used:

A link to my repo:

**Comment by trevorpreston** [comment]
hey Rawan,

I like this idea.  Before it's approved, can you fill in the missing information?  Especially these:

The models I need for my app and relationships:
Foreseen challenges or obstacles:
A link to my repo:


This is approved after you provide that info.  Thanks!

**Comment by Rawandahli** [comment]
I'll have three models, the relationship will be one to many from the departments model to the projects model and one to many from the projects model to the ideas. 

and here is the link to my repo 
https://github.com/Rawandahli/project-2
Foreseen challenges or obstacles:
Creating a web app with three models.

**Comment by trevorpreston** [comment]
I see that you have endpoints for departments and for ideas.  Will there be a route where you show the ideas by project?  What will that endpoint look like?

**Comment by Rawandahli** [comment]
Mr.Trever this is the new wireframe after changing the models.
https://wireframe.cc/x0J2RN

**Comment by trevorpreston** [comment]
very nice!  Approved 👍
