### ISSUE TITLE
Moroj-project2

### ISSUE THREAD

**Issue by morojAlh** [WDI-HoneyBadger/project-2#22]
Name of your app:
(About Space)

What your app does:
A website that collects data for Space (movies, apps, news) and the user can put the movies and apps in a favorite.

The models you need for your app and any relationships:
![project2](https://user-images.githubusercontent.com/37349702/49999862-f2544e00-ffa8-11e8-8d60-9f3a251f091d.png)

A timeline laying out what you're going to do each day. This should specify clear features to be implemented by the end of each day.
Sunday: create files, directories, database, insert some data and test the relationship, create the models.
Monday: write views files and design it.
Tuesday: write the controllers files and use the API.
Wednesday: test the design and editing files
Thursday: submit the project and getting ready for presentation.

A link to the NPM package you intend to use:
https://www.npmjs.com/package/apod-nasa

The technology you intend to use:
Maybe twitter API!

A link to your repo!
https://github.com/morojAlh/AboutSpace

**Comment by trevorpreston** [comment]
Hey Moroj,

This looks good!  How is the data entered in your database?  Is it user submitted or is it from an API?

**Comment by morojAlh** [comment]
Only admin can add (movie, app).

**Comment by morojAlh** [comment]
Or maybe for movies I will use imdb-api ( https://www.npmjs.com/package/imdb-api )

**Comment by trevorpreston** [comment]
Right sounds good.  I'd suggest that for V1 you have it so only the admin can add, then do the API later if you have time after completing V1.  Let me know if you get the API step!  Just want to make sure we keep your imdb keys off of github - there are a lot of bots that try to steal keys there.

Approved!
