### ISSUE TITLE
project2

### ISSUE THREAD

**Issue by Gothamey** [WDI-HoneyBadger/project-2#23]
youFilm is  a place where you can store information about movies and actors, television programs. rating, watchlist and maybe users and reviews 

https://wireframe.cc/Bz4Wm9

**Comment by trevorpreston** [comment]
Hey AK,

Can you fill this in with all the required info?

Your proposal should include:
Name of your app
What your app does
The models you need for your app and any relationships
Wireframes!
A timeline laying out what you're going to do each day. This should specify clear features to be implemented by the end of each day.
A link to the NPM package you intend to use.
Foreseen challenges or obstacles
Technology you intend to use
A link to your repo!

**Comment by trevorpreston** [comment]
Could you also add a route for /movies/:id/actors that shows all the actors in that movie?

**Comment by Starlordx24** [comment]
Yeah I will 👍🏻 
Also I’m thinking to add another model such as directors related to the movies id but I’m not sure and I don’t want to get confused and ran out of time specially with my exams as well. What do you recommend ?

**Comment by trevorpreston** [comment]
That's a good idea, but it'll definitely make the project harder.  How about you start with just actors for movies, then add the directors at the end if you have time.
