### ISSUE TITLE
Weallcan

### ISSUE THREAD

**Issue by hamoudsa** [WDI-HoneyBadger/project-2#24]
Basically my app kinda of platform for everyone who can provide a service or who needs a service, my view is connecting must people to each other so they can either trading service for another service, service for stuff they needs, opposite way too, but in this one Im foucsing in rental vehicles and bikes,, so we have an index page which has to link one for the provider of the service ( in my case owner of the car) and the other link for the customer ( the renter of the car),, 

I came up with this name (WNEO) which stand for We Need Each Other

**Comment by trevorpreston** [comment]
Hey Hamoud.  Can you update your proposal to fulfill all the proposal requirements?

Listed below:
Name of your app
What your app does
The models you need for your app and any relationships
Wireframes!
A timeline laying out what you're going to do each day. This should specify clear features to be implemented by the end of each day.
A link to the NPM package you intend to use.
Foreseen challenges or obstacles
Technology you intend to use
A link to your repo!


It's a good idea though.  Looking forward to reading this when you finish.

**Comment by hamoudsa** [comment]
> Hey Hamoud. Can you update your proposal to fulfill all the proposal requirements?
> 
> Listed below:
> Name of your app: WNEO(We Need Each Other) and I might change it
> What your app does:
The app that I am implementing is basically an app where providers can post their extra products or that are not in their use for the time being, and allow users rent the products that they needs . This will be an online application build on NodeJS. The providers can post the pictures of the product and add description of the product features. Moreover, the users can search for any products online just by typing the name of the product and the system will enlist all the products that match the searching criteria. Similarly, the users can login/sign in into the system. 
In my app I would focus on rental cars, so the user can search for any car type and model if I do have time I would add ( pick up / drop off location).
> The models you need for your app and any relationships:
Some of the models that I intend to use for this application are the login/sign in and the posting an ad functionality. I may wish to implement as many models as we want as we go on with the development stage of the project.
> Wireframes!
![screen shot 2018-12-17 at 15 16 08](https://user-images.githubusercontent.com/44431214/50087426-15813680-0211-11e9-9fcf-2db39691b639.png)
![screen shot 2018-12-17 at 15 23 52](https://user-images.githubusercontent.com/44431214/50087457-2a5dca00-0211-11e9-841d-cd7469c8f4ff.png)
![screen shot 2018-12-17 at 15 24 08](https://user-images.githubusercontent.com/44431214/50087466-2f227e00-0211-11e9-9c8d-30f9b19945e4.png)

> A timeline laying out what you're going to do each day. This should specify clear features to be implemented by the end of each day.
still implementing functions and testing sign up for customers and providers,, so in costumers would have search,, and in providers would be able to implement pic and adding descriptions.
> A link to the NPM package you intend to use.
pg-promise
Postgres sql
Body-parser
Express
Mustache-express
I may use some other package during the implementation depending upon the requirements.
> Foreseen challenges or obstacles
I am a little more thoughtful about the search functionality that I’m going to implement in this project.
> Technology you intend to use
Express packages
Node JS
Mustache 
Postgres sql
> A link to your repo!
> 
> It's a good idea though. Looking forward to reading this when you finish.
Thanks, and I will updated tonight also as soon as I'm done working on it.

**Comment by trevorpreston** [comment]
Looking good.  A couple more things to complete:

What are the models?  Models meaning tables.  You are going to have a users table and a... car table?  What is the relationship for that?

Could you add wireframes for the pages where someone posts an ad?  Then for the CRUD requirement - will a user be able to create, read, update and delete their posts?

Feel free to talk with me in person if there is any confusion here.  Let's wrap this up ASAP!

**Comment by hamoudsa** [comment]
![screen shot 2018-12-17 at 16 35 24](https://user-images.githubusercontent.com/44431214/50090517-d1466400-0219-11e9-95f0-02836329921a.png)

**Comment by trevorpreston** [comment]
👍
