### ISSUE TITLE
NoteM

### ISSUE THREAD

**Issue by muneerabaz** [WDI-HoneyBadger/project-2#25]
Its a note taking app , as a college student taking notes is extremely important but i could never find an app that have everything i wanted and easy to use  so i decided to build my on ( NoteM )  , my app is divided to many sections , a list for all of my college subjects that i am attending  ( Statistics , English , DataBase , operating System ) and each subject has its on titles depending on the lesson name or date and each lesson has its on notes . This notes can be deleted or edited . This website can be accessed by the author at anytime and anywhere . https://www.dropbox.com/s/xdytkruj19pnpzw/Screenshot%202018-12-14%2022.51.07.png?dl=0

**Comment by trevorpreston** [comment]
Looking good!  👍
