### ISSUE TITLE
Arts shine 

### ISSUE THREAD

**Issue by shuunz** [WDI-HoneyBadger/project-2#26]
“A life without art is in reality not a life at all. We all need art in our lives, and we'd be lying by denying it. “
**Arts shine** is an application that show my preferable photograph, and allow artists to share their arts with others.

**Models :**
- User.
- Image.

**Database :** 
- One to many relational database.

![arts shine database](https://user-images.githubusercontent.com/20524455/50046001-59f3c180-00ad-11e9-8b48-983c3d4c1b86.png)

**Wireframes :** 

<img width="607" alt="wireframe1" src="https://user-images.githubusercontent.com/20524455/50045999-52ccb380-00ad-11e9-8749-1d248acc86e9.png">

<img width="864" alt="wireframe2" src="https://user-images.githubusercontent.com/20524455/50045812-9f62bf80-00aa-11e9-9674-121e25621583.png">
<img width="865" alt="wireframe3" src="https://user-images.githubusercontent.com/20524455/50045813-a5f13700-00aa-11e9-9b78-902904c0048b.png">
<img width="863" alt="wireframe4" src="https://user-images.githubusercontent.com/20524455/50045815-abe71800-00aa-11e9-9055-5b93bffefca0.png">

**Npm package :** 
- Image upload.

**Technologies :** 
- JQ.
- HTML.
- CSS.
- SQL
- NPM.

**Comment by trevorpreston** [comment]
Hey Shahad,

This looks good, but the image upload is going to be a big challenge.  How do you plan to do this?  Can you send me an exact link to the NPM package you want to use?

**Comment by shuunz** [comment]
thank u,
by using npm Cloudinary that allow users to upload images ,
and this is the link https://medium.freecodecamp.org/how-to-allow-users-to-upload-images-with-node-express-mongoose-and-cloudinary-84cefbdff1d9

**Comment by trevorpreston** [comment]
Right ok.  I've never used it but I've heard Cloudinary is quite good.  It is very challenging though, so make sure you have a working test of it by Tuesday, ok?

**Comment by trevorpreston** [comment]
Approved 👍
