### ISSUE TITLE
B.log(' ');

### ISSUE THREAD

**Issue by YA7MO** [WDI-HoneyBadger/project-2#27]
* Name of your app
#### B.log(' ');
* What your app does
#### its a blog webpage for a blogger admin with functionalities to categorize articles and employ the use of markdown syntax. 
* The models you need for your app and any relationships
#### 3 models "for now" one for the AUTH of the page, one for the categories and one for the articles 
* Wireframes!
![untitled diagram pdf 1](https://user-images.githubusercontent.com/39294093/50046292-7a724a80-00b2-11e9-8438-861aad70ac17.png)

* A timeline laying out what you're going to do each day. This should specify clear features to be 
 implemented by the end of each day.
#### link everything together and add some last touches.

* A link to the NPM package you intend to use.
[Markdown](https://www.npmjs.com/package/markdown) 

* Foreseen challenges or obstacles
#### AUTH, since i have never used it before.

* Technology you intend to use
 #### login.js

* A link to your repo!
https://github.com/YA7MO/Project-2

**Comment by trevorpreston** [comment]
Pretty sure this is good.  Just want to clarify - are there non-admin users as well?

**Comment by YA7MO** [comment]
for now i'm working on the admin side and make sure he\she has a crud, once i'm done with that i will try to make a userside as well

**Comment by trevorpreston** [comment]
Right sounds good.  Approved 👍
