### ISSUE TITLE
WOW

### ISSUE THREAD

**Issue by Nalghamdi** [WDI-HoneyBadger/project-2#28]
**Name of your app**
World of Wedmin (WOW)

**What your app does**
Helps in wedding planning and finding suitable vendors.

**The models you need for your app and any relationships**
User, checklist, budget, items, guest list, vendors, categories/products. 
User will have one of budget, many checklist, items, guests and saves many vendors products. Vendor will have many products.
**wireframe**
Just a first draft 
<img width="624" alt="screen shot 2018-12-16 at 10 10 06 am" src="https://user-images.githubusercontent.com/44323973/50051027-eb4d4d00-011a-11e9-882a-2aa27436bc5e.png">

**timeline** 
Respectively: 
- Sketch the website and do the structures
- Create the database
- Models and controllers
- Views
- Styling and debugging

**A link to the NPM package you intend to use.**
[ChartJs](https://www.chartjs.org/docs/latest/)

**Foreseen challenges or obstacles**
Time-limits , user authentication 

**Technology you intend to use**
RESTFUL app using node.js packages, Html, CSS, jQuery/JS 

**A link to your repo!**
[WOW](https://github.com/Nalghamdi/WOW)

**Comment by Nalghamdi** [comment]
💯agree with you.

I have divided the work into phases and I will work on them one by one.   

_I'll challenge myself to complete as many parts as I can🏋🏼‍♀️._

**Comment by trevorpreston** [comment]
perfect!  I 🐝🍃 in u.

Approved 👍
