### ISSUE TITLE
Project #2- Online coaching

### ISSUE THREAD

**Issue by khalid1434** [WDI-HoneyBadger/project-2#30]
### What is the project?

The project is to provide bodybuilding exercises with some description along with trainers and their contact numbers. 

### Project Structure:
There will be two models, two controllers, one database and two tables.

### Database relations:
Since the project has two tables trainers table and exercises table. So, each trainer is going to train multiple exercises which will mean the relation is one to many.

https://files.slack.com/files-pri/TA2AHQDQ8-FEW4V3GQ7/img_20181216_123053.jpg

**Comment by trevorpreston** [comment]
looking good!  👍
