### ISSUE TITLE
Project 2 Book Collection

### ISSUE THREAD

**Issue by NawafI** [WDI-HoneyBadger/project-2#31]
My app is Book Collection. It does track books I want to read. I am using two models one for list of textbooks and second for authors. The technology I am going to use are HTML, CSS, JavaScript, and SQL. The timeline for today I am going to collect data for my books. Tomorrow, I will make books pages. Tuesday, I will make author pages. Wednesday, I will do styling and make sure everything is fine and the app is working.

My wireframe : https://wireframe.cc/l1Nr9y

Link of my repo : 
![image](https://user-images.githubusercontent.com/44641637/50054435-cbd21680-0152-11e9-8121-f1f46efb69f9.png)

**Comment by trevorpreston** [comment]
looks good!
