### ISSUE TITLE
Project 2 be rich

### ISSUE THREAD

**Issue by Masarsah** [WDI-HoneyBadger/project-2#4]
Name of your app: be rich
What your app does: calculate , display
The models: user portfolio and budget
![berich](https://user-images.githubusercontent.com/38545469/49942982-d5ac0d80-fef7-11e8-81d2-71f4274696c1.jpg)

A timeline:
implemented by the end of each day.
A link to the NPM package:https://www.npmjs.com/package/graph-js
Technology: javascript , html , Css
A link to your repo!:
https://github.com/Masarsah?tab=repositories

**Comment by trevorpreston** [comment]
We talked about this offline, but your models are users and transactions, right?  We had said that budget should be included as part of the user model.  Is that still the plan?

Let me know!  Other than that, looking good 👍

**Comment by Masarsah** [comment]
yeah I did that two model user and transaction

**Comment by trevorpreston** [comment]
sounds good!
