### ISSUE TITLE
The Sultan Scores - Project 2

### ISSUE THREAD

**Issue by SultanBS** [WDI-HoneyBadger/project-2#6]
### Proposal
**Name of your app:**
The Sultan Score.

**What your app does:**
It gives you all the scores for football games(Soccer) and you can choose which league you want to see the scores. 

**The models you need for your app and any relationships: **
Models: At least one for teams and one for leagues. 
Tables: 3 teams, tables, and a joint table.

**Wireframes:** 

![project proposal](https://user-images.githubusercontent.com/44410189/50051536-661b6580-0125-11e9-8be2-70fcaaa2c913.PNG)

**Timeline:-**
**Sunday:** Creating the structure and Learn API and fetch npm.
**Monday:** Finishing the database along with the configuration.
**Tuesday:** Finishing Models and Controllers.
**Wednesday:** Finishing Views and CSS and maybe adding new features.
**Thursday:** Fixing bugs and doing presentation.

**A link to the NPM package you intend to use:**
express, mustach, body-parser, pg-promise, and method-override morgan, and maybe fetch.

**Foreseen challenges or obstacles:**
- Learn API in a short time.
- Finishing a big database.
- Make the project functional. 

**Technology you intend to use:**
- HTML.
- CSS.
- JS
- NodeJS.
- NPM
- Postgresql.

**Link to the repo:** 
https://github.com/SultanBS/TheSultanScores.git

**Comment by trevorpreston** [comment]
Fill us in a little here - what is this app and what does it do?

**Comment by SultanBS** [comment]
Finished the editing of the proposal. 💯

**Comment by trevorpreston** [comment]
Dear other instructors:

I talked offline with Sultan.  He's going forward with this but with on Read functionality for Leagues, then he'll add in the CUD later if there is time.  Additionally, he'll be seeding dummy data to start with. 
 He's been warned about the scope.

Right @SultanBS ?

**Comment by SultanBS** [comment]
Yes @trevorpreston , you took the words out of my mouth :)) 👍 This is my plan.

**Comment by trevorpreston** [comment]
perfect.  Approved 👍
