### ISSUE TITLE
project 2 school app

### ISSUE THREAD

**Issue by abdulrabbt** [WDI-HoneyBadger/project-2#7]
name app : school app

school admin can add new student and edite grade and delete student
and student can see final grade for course .

link : https://wireframe.cc/LkBoel

I have 2 models, one for student and another for admin
I have 2 controllers, one for student and another for admin

repo link: https://github.com/abdulrabbt/Project-2

NPM package : https://www.npmjs.com/package/bootstrap

**Comment by trevorpreston** [comment]
hey Abdulrab,

I like the idea, but could use some clarification on some points.  I only see one wireframe here - is your project only one page?

**Comment by trevorpreston** [comment]
Looks good 👍
